<a href="https://colab.research.google.com/github/stevengiacalone/Python-workshop/blob/main/Session_2_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

Welcome to Session 2 of the Python workshop. Today, we'll be biscussing NumPy, a popular library for storing arrays of numbers and performing computations on them. Not only this enables to write often more succint code, this also makes the code faster, since most NumPy routines are implemented in C for speed.

Before we dive in, some attributions:
- Parts of this notebook are taken or adapted from tutorials by Mathieu Blondel and Fraida Fund.
- Parts of this notebook are adapted from a tutorial from CS231N at Stanford University, which is shared under the MIT license.
- Parts of this notebook are adapted from Jake VanderPlas’s Whirlwind Tour of Python, which is shared under the Creative Commons CC0 Public Domain Dedication license.
- The visualizations in this notebook are from A Visual Intro to NumPy by Jay Alammar, which is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
- Parts of this notebook (and some images) about numpy broadcasting are adapted from Sebastian Raschka’s STATS451 materials.

More info on NumPy can be found in the NumPy website: https://numpy.org/doc/stable/user/index.html#user

To use NumPy in your program, you need to import it as follows. This is the standard way to import all Python libraries and modules.

In [3]:
import numpy as np

## Array creation



#### Creating arrays with arbitrary dimensions

NumPy arrays can be created from Python lists

In [4]:
my_array = np.array([1, 2, 3])
my_array

array([1, 2, 3])

This creates the array we can see below:

![](http://jalammar.github.io/images/numpy/create-numpy-array-1.png)

NumPy supports array of arbitrary dimension. For example, we can create two-dimensional arrays (e.g. to store a matrix) as follows

In [5]:
my_2d_array = np.array([[1, 2], [3, 4]])
my_2d_array

array([[1, 2],
       [3, 4]])

Here is another visualization:

![](http://jalammar.github.io/images/numpy/numpy-array-create-2d.png)

Laslty, let's make a three-dimensional array.

In [8]:
my_3d_array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
    ])
my_3d_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

![](http://jalammar.github.io/images/numpy/numpy-3d-array.png)

You can check the shape of an array like so

In [9]:
print(my_array.shape)
print(my_2d_array.shape)
print(my_3d_array.shape)

(3,)
(2, 2)
(2, 2, 2)


Lastly, you can reshape arrays using the `.reshape` and `.flatten` methods.

In [27]:
this_1D_array = np.array([1, 2, 3, 4, 5, 6])
print(this_1D_array)

this_2D_array = this_1D_array.reshape((3,2)) # the number of elements needs to remain constant after the reshaping
print(this_2D_array)

this_1D_array2 = this_2D_array.flatten() # reverts the array back to 1 dimension
print(this_1D_array2)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


#### Setting the data type of an array

Contrary to Python lists, NumPy arrays must have a type and all elements of the array must have the same type.

In [ ]:
my_array.dtype

dtype('int64')

The main types are `int32` (32-bit integers), `int64` (64-bit integers), `float32` (32-bit real values) and `float64` (64-bit real values).

The `dtype` can be specified when creating the array

In [ ]:
my_array = np.array([1, 2, 3], dtype=np.float64)
my_array.dtype

dtype('float64')

#### Initializing N-D arrays with "placeholder" values


You can create arrays of arbitrary shape and size using the functions `np.zeros`, `np.ones`, and `np.full`. This is useful for initializing arrays that you will later edit.

In [10]:
zeros_array = np.zeros(shape=(3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
ones_array = np.ones(shape=(3,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
elevens_array = np.full(shape=(3,3), fill_value=11) # you can set fill_value to anything
elevens_array

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

You can also make arrays with random values between zero and one using `np.random.random`.

In [13]:
random_array = np.random.random(size=(3,3))
random_array

array([[0.37383208, 0.8454054 , 0.5775575 ],
       [0.81165519, 0.57581227, 0.08610639],
       [0.81480639, 0.91730608, 0.55832865]])

#### Creating arrays with increasing values

You can create arrays in which the values of the elements increase an regular intervals using `np.arange` and `np.linspace`.

In [18]:
increasing_array1 = np.arange(start=0, stop=12, step=2)
print(increasing_array1)

increasing_array2 = np.arange(20) # default start value is 0 and default step size is 1, so you can usually just specify the end value
print(increasing_array2)

[ 0  2  4  6  8 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
increasing_array3 = np.linspace(start=0, stop=10, num=20) # with np.linspace you specify the total number of elements, rather than the step size
print(increasing_array3) # all values will be evenly spaced

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


## Array indexing

#### Basic indexing and slicing

We can index and slice numpy arrays in all the ways we can slice Python lists:

![](http://jalammar.github.io/images/numpy/numpy-array-slice.png)

And you can index and slice numpy arrays in multiple dimensions. If slicing an array with more than one dimension, you should specify a slice for each dimension:

![](http://jalammar.github.io/images/numpy/numpy-matrix-indexing.png)

In [28]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [29]:
print(a[0, 1])
b[0, 0] = 10    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

2
10


You can also mix integer indexing with slicing to get specific rows/columns from your N-D array.

In [31]:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# let's get the middle row of the array a
middle_row = a[1, :]
print(middle_row)

# now let's get the second column
middle_col = a[:, 1]
print(middle_col)

[5 6 7 8]
[ 2  6 10]


#### Integer array indexing

When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [33]:
a = np.array([
      [1, 2],
      [3, 4],
      [5, 6]
    ])

# An example of integer array indexing.
# The returned array will have shape (3,)
print(a[[0, 1, 2], [0, 1, 0]])

[1 4 5]


#### Boolean array indexing

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [34]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [35]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


#### Finding specific indices

When working with numpy arrays, it’s often helpful to get the *indices* (not only the values) of array elements that meet certain conditions. There are a few numpy functions that you’ll definitely want to remember:

-   [`argmax`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) (get index of maximum element in array)
-   [`argmin`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) (get index of minimum element in array)
-   [`argsort`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) (get sorted list of indices, by element value, in ascending order)
-   [`where`](https://numpy.org/doc/stable/reference/generated/numpy.where.html) (get indices of elements that meet some condition)

In [36]:
a = np.array([1, 8, 9, -3, 2, 4, 7, 9])

# Get the index of the maximum element in a
print(np.argmax(a))

# Get the index of the minimum element in a
# (this array has two elements with the maximum value -
# only one index is returned)
print(np.argmin(a))

# Get sorted list of indices
print(np.argsort(a))

# Get sorted list of indices in descending order
# [::-1] is a special slicing index that returns the reversed list
print(np.argsort(a)[::-1])

# Get indices of elements that meet some condition
# this returns a tuple, the list of indices is the first entry
# so we use [0] to get it
print(np.where(a > 5)[0])

# Get indices of elements that meet some condition
# this example shows how to get the index of *all* the max values
print(np.where(a >= a[np.argmax(a)])[0])

2
3
[3 0 4 5 6 1 2 7]
[7 2 1 6 5 4 0 3]
[1 2 6 7]
[2 7]


## Math with NumPy

NumPy makes it easy to do math with built-in constants, functions, and operations. Let's explore a few of these below.

#### Constants

First off, NumPy has a bunch of pre-defined constants that will come in handy.

In [44]:
print("pi = ", np.pi)
print("e =", np.e)
print("infinity =", np.inf)
print("not a number =", np.nan)

pi =  3.141592653589793
e = 2.718281828459045
infinity = inf
not a number = nan


#### Arithmetic operations

Arithmetic operations can be performed directly over arrays. For instance, assuming two arrays have a compatible shape, we can add them as follows

In [50]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
array_a + array_b

array([5, 7, 9])

Note that adding lists does not work this way. This is what happens if you try to add two lists in this way.

In [46]:
list_a = [1, 2, 3]
list_b = [4, 5, 6]
list_a + list_b

[1, 2, 3, 4, 5, 6]

If you want to add a list element-wise, you need to add a loop. This is MUCH less efficient, and will increase the runtime of your code significantly. It's always better to use NumPy if you can!

In [49]:
array_out = np.zeros_like(array_a)
for i in range(len(array_a)):
    array_out[i] = array_a[i] + array_b[i]
array_out

array([5, 7, 9])

Other arithmetic operations (subtraction, multiplication, division) work the same.

#### Universal functions

In NumPy, functions that operates on arrays in an element-wise fashion are called [universal functions](https://numpy.org/doc/stable/reference/ufuncs.html). Here are a few, to give you an idea:

In [54]:
print(np.sin(array_a)) # sine function
print(np.cos(array_a)) # cosine function
print(np.exp(array_a)) # exponential
print(np.log(array_a)) # natural logarithm
print(np.log10(array_a)) # base-10 logarithm
print(np.sqrt(array_a)) # square root

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[1.         1.41421356 1.73205081]


Some other useful functions include:
- np.max() and np.min(): return the max and min elements of an array
- np.sum(): returns the sum of all elements in an array
- np.mean(), np.median(), np.std(): return the average, median, and standard deviation of elements in an array

Here are some visualizations of how they work:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-1.png)

You can also specify an axis to perform the operation over:

![](http://jalammar.github.io/images/numpy/numpy-matrix-aggregation-4.png)

There are tons of others. You can usually find a function that meets your needs via a Google search.

#### Matrix math

You can also treat NumPy arrays like vectors and matrices. The function `np.dot` takes the inner product of two 1D arrays, multiply a vector by a matrix, or multiply two matrices.

In [56]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(np.dot(v, w))
print(v @ w)

219
219


In [59]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]


In [58]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Matrix transpose can be done using `.transpose()` or `.T` for short

In [60]:
my_array = np.array([[1,2,3],
                     [4,5,6]]
                   )
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.

For example: basic linear algebra, we can only add (and perform similar element-wise operations) two matrics that have the *same* dimension. In numpy, if we want to add two matrics that have different dimensions, numpy will implicitly “extend” the dimension of one matrix to match the other so that we can perform the operation.

Here are some examples of when broadcasting *works*:

**Case 1**: When the two arrays have the same dimensions. This is just the normal case of adding two arrays.



**Case 2**: When adding a single number to an array, the single number is stretched in N dimension to match the shape of the array.

In [71]:
a = np.array([[1,2], [3,4], [5,6]])
b = 1
c = a + b
c

# Visualization
#
#   [1, 2]       [1, 2]   [1, 1]   [1+1, 2+1]   [2, 3]
#   [3, 4] + 1 = [3, 4] + [1, 1] = [3+1, 4+1] = [4, 5]
#   [5, 6]       [5, 6]   [1, 1]   [5+1, 6+1]   [6, 7]
#

array([[2, 3],
       [4, 5],
       [6, 7]])

**Case 3**: When each array has only 1 dimension, but along different axes, both arrays are stretched.

In [67]:
a = np.array([[4], [5], [6]])
b = np.array([1, 2, 3])
c = a + b
c

# Visualization
#
#   [4]   [1, 2, 3]   [4, 4, 4]   [1, 2, 3]   [4+1, 4+2, 4+3]   [5, 6, 7]
#   [5] +           = [5, 5, 5] + [1, 2, 3] = [5+1, 5+2, 5+3] = [6, 7, 8]
#   [6]               [6, 6, 6]   [1, 2, 3]   [6+1, 6+2, 6+3]   [7, 8, 9]
#

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

**Case 4**: If the shapes of the two arrays match along one axis and the size of the non-matching axis of the smaller array is 1, that axis gets stretched.

In [68]:
a = np.array([[4,5], [6,7], [8,9]])
b = np.array([[1],[2],[3]])
c = a + b
c

# Visualization
#
#   [4, 5]   [1]   [4, 5]   [1, 1]   [4+1, 5+1]   [5,  6 ]
#   [6, 7] + [2] = [6, 7] + [2, 2] = [6+2, 7+2] = [8,  9 ]
#   [8, 9]   [3]   [8, 9]   [3, 3]   [8+3, 9+3]   [11, 12]
#

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [70]:
a = np.array([[4,5], [6,7], [8,9]])
b = np.array([1, 2])
c = a + b
c

# Visualization
#
#   [4, 5]   [1, 2]   [4, 5]   [1, 2]   [4+1, 5+2]   [5, 7 ]
#   [6, 7] +        = [6, 7] + [1, 2] = [6+1, 7+2] = [7, 9 ]
#   [8, 9]            [8, 9]   [1, 2]   [8+1, 9+2]   [9, 11]
#

array([[ 5,  7],
       [ 7,  9],
       [ 9, 11]])

Broadcasting will *fail* if the two arrays do not have any common axes with the same lengths.

In [72]:
a = np.array([[4,5], [6,7], [8,9]])
b = np.array([1, 2, 3])
c = a + b
c

# Visualization
#
#   [4, 5]   [1, 2, 3]
#   [6, 7] +           = error
#   [8, 9]
#

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

You can find more info on broadcasting here: https://numpy.org/doc/stable/user/basics.broadcasting.html

## Exercises

**Exercise 1.** Create a 3d array of shape (2, 2, 2), containing 8 values. Access individual elements and slices.

**Exercise 2**. Create a 1D, 1000-element array that ranges from zero to $\pi$. Calculate the sine of the array using NumPy and return the index and value of the element in the array at which the sine function is maximized.

**Exercise 3.** Rewrite the relu function using `np.vstack` and `np.max`. Make it work on an array first, but if you want an extra challenge make it also work on a standard int or float datatype.

$\text{relu}(x) = \left\{
   \begin{array}{rl}
     x, & \text{if }  x \ge 0 \\
     0, & \text{otherwise }.
   \end{array}\right.$\

In [ ]:
def relu_numpy(x):
  return

relu_numpy(np.array([1, -3, 2.5]))

**Exercise 4.** Rewrite the [Euclidean norm](https://en.wikipedia.org/wiki/Norm_(mathematics) of a vector (1d array) using NumPy (without for loop)

In [ ]:
def euclidean_norm_numpy(x):
  return

my_vector = np.array([0.5, -1.2, 3.3, 4.5])
euclidean_norm_numpy(my_vector)

**Exercise 5.** Write a function that computes the Euclidean norms of a matrix (2d array) in a row-wise fashion. Hint: use the `axis` argument of [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html).

In [ ]:
def euclidean_norm_2d(X):
  return

my_matrix = np.array([[0.5, -1.2, 4.5],
                      [-3.2, 1.9, 2.7]])
# Should return an array of size 2.
euclidean_norm_2d(my_matrix)